### ISSUE TITLE
BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by danbayliss** [DavidMStraub/homeassistant-homeconnect#96]
Hi
When rebooting Home Assistant I see the following in my logs and have seen them for a few versions now but was wondering if you are aware of this?

![Screenshot_1](https://user-images.githubusercontent.com/54558493/86662722-e3971700-bfe4-11ea-89b4-f08ba3d4a250.png)
![Screenshot_2](https://user-images.githubusercontent.com/54558493/86662725-e3971700-bfe4-11ea-8241-7a781704e0b7.png)

**Comment by DavidMStraub** [comment]
This is fixed in master: https://github.com/DavidMStraub/homeassistant-homeconnect/commit/0e3a9838cdeb6d1f3f2941a3e0c719c320b23b53

**Comment by danbayliss** [comment]
Apologies i'm pretty new to github but do I need to wait for you to release this new version or should it be live now? I've got v1.0.1 installed already and still seeing this error
